# Generated by Django 4.1.3 on 2022-11-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_issued_charged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Late',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=7)),
                ('fine', models.CharField(max_length=5)),
            ],
        ),
    ]
